# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25dd03a358a619a552c50813f3e635c9fac4497bf860aaca49d3c83fea36e1b8bce5a3ec0802937e0b7c06622388d8c432285ec658b094e2d9199573eadbcf2

test:
  secret_key_base: 7fabad05c74f066bee8caf4c45962b239269e8181b1229b76b96c9abfbf0497a11c381ea29687206e39fb872af03b8b029fe84aa66100ffbbd28d7fca31ad099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
